# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build integration

on:
  push:
    tags:
      - "*"
env:
  AZURE_WEBAPP_PACKAGE_PATH: "build" # set this to the path to your web app project, defaults to the repository root
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  PROJECT: DEVOPS-Demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Build notification
        if: always()
        uses: edge/simple-slack-notify@master
        with:
          channel: "#devops"
          status: ${{ job.status }}
          success_text: "Build (#${env.GITHUB_RUN_NUMBER}) completed successfully"
          failure_text: "Build (#${env.GITHUB_RUN_NUMBER}) failed"
          cancelled_text: "Build (#${env.GITHUB_RUN_NUMBER}) was cancelled"
          fields: |
            [{ "title": "Integration Devops", "value": "#${env.PROJECT}"}]

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ewz-devops-demo"
          slot-name: "integration"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_9953091c739f4c10845cfcdd16536309 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy notification
        if: always()
        uses: edge/simple-slack-notify@master
        with:
          channel: "#devops"
          status: ${{ job.status }}
          success_text: "Deployment (#${env.GITHUB_RUN_NUMBER}) completed successfully"
          failure_text: "Deployment (#${env.GITHUB_RUN_NUMBER}) failed"
          cancelled_text: "Deployment (#${env.GITHUB_RUN_NUMBER}) was cancelled"
          fields: |
            [{ "title": "Integration Devops", "value": "#${env.PROJECT}"},{ "title": "Host", "value": "https://ewz-devops-demo-integration.azurewebsites.net/"}]
